on:
  push:
    branches:
      - main
      - develop
name: Test Workflow
jobs:
  sonarCloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      run:  npm install
    - name: Install Jest globally
      run:  sudo npm install -g jest
    - name: Run Tests
      run:  npm run test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
